# Generated by Django 5.2.1 on 2025-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("image", models.CharField(max_length=90)),
                ("release_data", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
